#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'build-essential'
cookbook 'apt'
cookbook 'apache2'
cookbook 'mysql'
cookbook 'php'
cookbook 'composer'
cookbook 'git'
cookbook 'rvm'
cookbook 'rubygems'
cookbook 'java'
cookbook 'maven'
cookbook 'memcached'
cookbook 'maven'
cookbook 'mongodb'
cookbook 'nodejs'
cookbook 'simple_iptables'
cookbook 'subversion'
cookbook 'drush',
	:github => 'msonnabaum/chef-drush'
cookbook 'icu',
	:github => 'Svatbata/chef-icu'
cookbook 'webapp',
	:github => "manosriglis/web-app"
